/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'snojo' at '10/29/15 4:00 PM' with Gradle 2.8
 *
 * @author snojo, @date 10/29/15 4:00 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
